import {
  ActivityEvent,
  AssessmentSessionDetail,
  CandidateInvite,
  CandidateProfile,
  EvaluationReportDetail,
  ProviderMetadata,
} from "@/lib/api/types";

export interface CandidateProfileViewModel {
  id: string;
  displayName: string;
  targetRole: string;
  university: string;
  skills: string[];
  techStack: string[];
  availabilityStatus: string;
  profileComplete: boolean;
  profileVisible: boolean;
}

export interface CandidateAssessmentViewModel {
  sessionId: string;
  status: string;
  targetRole: string;
  totalQuestions: number;
  answeredQuestions: number;
  currentQuestionIndex: number;
  progressPercent: number;
}

export interface CandidateReportViewModel {
  reportId: string;
  sessionId: string;
  verifiedScore: number;
  aiTestScore: number;
  integrityScore: number;
  published: boolean;
  recruiterSummary: string;
  providerLabel: string;
  providerFallbackUsed: boolean;
}

export interface CandidateInviteViewModel {
  id: string;
  companyName: string;
  recruiterName: string;
  roleTitle: string;
  opportunityType: string;
  salaryRange: string;
  interviewWindow: string;
  status: string;
  message: string;
  responseMessage: string;
  createdAt: string;
  respondedAt: string | null;
}

export interface CandidateActivityViewModel {
  id: string;
  type: string;
  title: string;
  description: string;
  entityType: string;
  entityId: string;
  createdAt: string;
}

function clampPercent(value: number): number {
  return Math.max(0, Math.min(100, Math.round(value)));
}

export function normalizeProviderMetadata(metadata?: ProviderMetadata): ProviderMetadata | undefined {
  if (!metadata) return undefined;
  const actualProvider = metadata.actual_provider || metadata.provider || "unknown";
  return {
    ...metadata,
    actual_provider: actualProvider,
    provider: actualProvider,
    fallback_chain: metadata.fallback_chain ?? [actualProvider],
    warnings: metadata.warnings ?? [],
  };
}

export function providerActualName(metadata?: ProviderMetadata): string {
  const normalized = normalizeProviderMetadata(metadata);
  return normalized?.actual_provider || "unknown";
}

export function providerLabel(metadata?: ProviderMetadata): string {
  const provider = providerActualName(metadata).toLowerCase();
  if (provider === "openrouter") return "OpenRouter";
  if (provider === "nvidia") return "NVIDIA Nemotron";
  if (provider === "gemini") return "Google Gemini";
  if (provider === "stub") return "Stub fallback";
  return provider === "unknown" ? "Unknown provider" : provider;
}

export function providerStatusText(metadata?: ProviderMetadata): string {
  const normalized = normalizeProviderMetadata(metadata);
  if (!normalized) return "AI provider metadata unavailable.";
  const label = providerLabel(normalized);
  if (normalized.fallback_used) {
    return `Generated by ${label} after provider fallback.`;
  }
  return `Generated by ${label}.`;
}

export function candidateProfileToViewModel(profile: CandidateProfile): CandidateProfileViewModel {
  return {
    id: profile.id,
    displayName: profile.full_name || "Candidate",
    targetRole: profile.target_role || "Target role not set",
    university: profile.university || "University not set",
    skills: profile.skills ?? [],
    techStack: profile.tech_stack ?? [],
    availabilityStatus: profile.availability_status || "open",
    profileComplete: profile.profile_complete,
    profileVisible: profile.profile_visibility,
  };
}

export function assessmentSessionToViewModel(
  detail: AssessmentSessionDetail
): CandidateAssessmentViewModel {
  const answered = detail.progress?.answered ?? detail.answers.length;
  const total = detail.progress?.total ?? detail.session.total_questions;
  return {
    sessionId: detail.session.id,
    status: detail.session.status,
    targetRole: detail.session.target_role || "Target role",
    totalQuestions: total,
    answeredQuestions: answered,
    currentQuestionIndex: detail.progress?.current_order_index ?? detail.session.current_order_index,
    progressPercent: total ? clampPercent((answered / total) * 100) : 0,
  };
}

export function evaluationReportToCandidateViewModel(
  report: EvaluationReportDetail
): CandidateReportViewModel {
  const providerMetadata = normalizeProviderMetadata(report.report_json.provider_metadata);
  return {
    reportId: report.id,
    sessionId: report.session_id,
    verifiedScore: clampPercent(report.verified_score),
    aiTestScore: clampPercent(report.ai_test_score),
    integrityScore: clampPercent(report.integrity_score),
    published: report.published,
    recruiterSummary: report.recruiter_summary,
    providerLabel: providerLabel(providerMetadata),
    providerFallbackUsed: providerMetadata?.fallback_used ?? false,
  };
}

export function candidateInviteToViewModel(invite: CandidateInvite): CandidateInviteViewModel {
  return {
    id: invite.id,
    companyName: invite.company.company_name || "Company",
    recruiterName: invite.company.recruiter_name || "Recruiter",
    roleTitle: invite.role_title,
    opportunityType: invite.opportunity_type,
    salaryRange: invite.salary_range || "Not specified",
    interviewWindow: invite.interview_window || "To be scheduled",
    status: invite.status,
    message: invite.message,
    responseMessage: invite.response_message || "",
    createdAt: invite.created_at,
    respondedAt: invite.responded_at,
  };
}

export function activityEventToViewModel(event: ActivityEvent): CandidateActivityViewModel {
  return {
    id: event.id,
    type: event.event_type,
    title: event.title,
    description: event.description,
    entityType: event.entity_type,
    entityId: event.entity_id,
    createdAt: event.created_at,
  };
}
